export const TESTING_ONE = "TESTING_ONE";
export const TESTING_TWO = "TESTING_TWO";
export const CONNECT_PORT = "CONNECT_PORT";
export const MESSAGE_PORT = "MESSAGE_PORT";
export const DISCONNECT_PORT = "DISCONNECT_PORT";
export const SET_APP_VISIBILITY = "SET_APP_VISIBILITY";


export default {
    TESTING_ONE,
    TESTING_TWO,
    CONNECT_PORT,
    MESSAGE_PORT,
    DISCONNECT_PORT
}