export const TESTING_ONE = "TESTING_ONE";
export const TESTING_TWO = "TESTING_TWO";
export const CONNECT_PORT = "CONNECT_PORT";
export const MESSAGE_PORT = "MESSAGE_PORT";
export const DISCONECT_PORT = "DISCONECT_PORT";
export const DISCONECT_PORTS = "DISCONECT_PORTS";
export const BROWSER_ACTION_TRIGGERED = "BROWSER_ACTION_TRIGGERED";

export default {
    TESTING_ONE,
    TESTING_TWO,
    CONNECT_PORT,
    MESSAGE_PORT,
    DISCONECT_PORT,
    DISCONECT_PORTS,
    BROWSER_ACTION_TRIGGERED
}