export const TESTING_ONE = "TESTING_ONE";
export const TESTING_TWO = "TESTING_TWO";
export const CONNECT_PORT = "CONNECT_PORT";
export const MESSAGE_PORT = "MESSAGE_PORT";
export const DISCONECT_PORT = "DISCONECT_PORT";
export const STILL_ALIVE = "STILL_ALIVE";
export const TOOLBAR_BUTTON_PRESSED = "TOOLBAR_BUTTON_PRESSED";
export const SET_APP_VISIBILITY = "SET_APP_VISIBILITY";



export default {
    TESTING_ONE,
    TESTING_TWO,
    CONNECT_PORT,
    MESSAGE_PORT,
    DISCONECT_PORT,
    STILL_ALIVE,
    TOOLBAR_BUTTON_PRESSED,
    SET_APP_VISIBILITY
}